---
abstract: A selection of subroutines supporting ANSI escape sequence handling
author:
  - 'Josef <josef@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Ecma48-Util
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Exporter: 0
  Test::More: 0
  perl: 5.014
  re: 0
version: 0.01
